### ISSUE TITLE
loop requests

### ISSUE THREAD

**Issue by brettowe** [ebarkie/weatherlink#1]
just found your package and I grabbed the example code and it fetchs archive packets just fine
but I'm more interested in current conditions which mean loop packets from what I see in serial docs
so I changed the code to do
w.CmdQ <- weatherlink.CmdGetLoops
with 10s timeout I saw nothing
increasing to 20s archive packets would start coming in
increased again to 50s and still archive only
so Ideas? looking at the code I'm wonder if using LOOP would be better than LPS ?

**Comment by ebarkie** [comment]
I suspect the loops are getting starved by it prioritizing archives.  What you're looking to do is perfectly reasonable but at the moment it doesn't have a good toggle for disabling reading archives.

You could try two things:

1) In your driver code enable all logging levels so you can see what's going on:

```
import "os"

weatherlink.Error.SetOutput(os.Stdout)
weatherlink.Warn.SetOutput(os.Stdout)
weatherlink.Info.SetOutput(os.Stdout)
weatherlink.Debug.SetOutput(os.Stdout)
weatherlink.Trace.SetOutput(os.Stdout)
```

2) The quick and dirty fix is probably just to comment out the archive logic in protocol.go/Start()'s case statement:

```
case CmdGetDmps: 
    //w.LastDmpTime, err = w.getDmps(ec, w.LastDmpTime)      
```

When I get a chance I'll try to test this and come up with a better solution.

It uses LPS rather than LOOP to interleave both LOOP and LOOP2 packets.  The LOOP2's have some useful computed values...

**Comment by brettowe** [comment]
here is a log 
looks like it gets 1 loop but doesn't pass it on
and then gives up on loop due to another command being requested and looking at the example code only 1 command is ever requested?
so my thoughts on the LOOP vs. LPS is moot after seeing this
I was assuming LPS just wasn't sending

[logfile.txt](https://github.com/ebarkie/weatherlink/files/1273311/logfile.txt)

**Comment by ebarkie** [comment]
Thanks.  Yeah it's what I thought it was,  it's insisting on catching up on archive records.

Did you try #2 that I listed above? Commenting out that one line should should get you going but I'll a proper fix in there soon.

**Comment by brettowe** [comment]
no I did't try out #2 I'm not in a rush to have it working, I just had a little time to see how the code worked and returned data so I can start formulating a plan of attack for a project

**Comment by ebarkie** [comment]
The latest commit should resolve this.  It will no longer force archive downloads on start nor will it preempt a loop cycle to retrieve a new archive record unless a CmdGetDmps was explicitly sent at least once.

**Comment by brettowe** [comment]
did a go get and did go build and its still giving archives
modified my program a bit to reflect your example as far as debug level below is what it gave
sorry to say doesn't look to be fixed to me

2017/09/15 10:15:54 Opened station
2017/09/15 10:15:54 Receiving events for 15s
2017/09/15 10:15:54 Command broker started
[INFO]2017/09/15 10:15:54 Retrieving 165 loop packets
[INFO]2017/09/15 10:16:05 Retrieved archive record for 2017-07-24 02:30:00 -0700 PDT
[INFO]2017/09/15 10:16:05 Retrieved archive record for 2017-07-24 03:00:00 -0700 PDT
2017/09/15 10:16:05 Received archive record: 
2017/09/15 10:16:05 Received archive record: 
[INFO]2017/09/15 10:16:06 Retrieved archive record for 2017-07-24 03:30:00 -0700 PDT
[INFO]2017/09/15 10:16:06 Retrieved archive record for 2017-07-24 04:00:00 -0700 PDT

**Comment by ebarkie** [comment]
Since you already have an old version please do a "go get -u" to be sure it's the latest version with the fix.

Barring that, make sure you are not setting LastDmpTime (it should be left as its zero value) or sending a CmdGetDmps command.  If you do either of those things it's assumed you are interested in archive records and it will begin proactively pulling new records as soon as they're available.

If none of that resolves it can you please provide the complete driver for your test so I can try to re-create it? Thanks..

**Comment by brettowe** [comment]
looks like it was just outdated code using -u fixed it 
thanks

2017/09/16 10:39:56 Opened station
2017/09/16 10:39:56 Receiving events for 15s
2017/09/16 10:39:56 Command broker started
[INFO]2017/09/16 10:39:57 Retrieving 165 loop packets
2017/09/16 10:39:57 Received loop packet: {Bar:{Altimeter:30.167 SeaLevel:29.987 Station:25.108 Trend:Steady} Bat:{ConsoleVoltage:4.1484375 TransStatus:0} DewPoint:29 ET:{Today:0 LastMonth:0 LastYear:0} ExtraHumidity:[<nil> <nil> <nil> <nil> <nil> <nil> <nil>] ExtraTemp:[<nil> <nil> <nil> <nil> <nil> <nil> <nil>] Forecast:Increasing clouds with little temperature change. HeatIndex:56 Icons:[Cloud Partly Cloudy] InHumidity:44 InTemp:69.3 LeafTemp:[<nil> <nil> <nil> <nil>] LeafWetness:[<nil> <nil> <nil> <nil>] OutHumidity:31 OutTemp:60.1 Rain:{Accum:{Last15Min:0 LastHour:0 Last24Hours:0 Today:0 LastMonth:0.57 LastYear:1.54 Storm:0} Rate:0 StormStartDate:0001-01-01 00:00:00 +0000 UTC} SoilMoist:[<nil> <nil> <nil> <nil>] SoilTemp:[<nil> <nil> <nil> <nil>] SolarRad:32767 Sunrise:2017-09-16 06:37:00 -0700 PDT Sunset:2017-09-16 19:00:00 -0700 PDT THSWIndex:32767 UVIndex:25.5 Wind:{Avg:{Last2MinSpeed:5.4 Last10MinSpeed:4.1} Cur:{Dir:6 Speed:7} Gust:{Last10MinDir:360 Last10MinSpeed:0.8}} WindChill:60 nextArchRec:2072}
2017/09/16 10:39:58 Received loop packet: {Bar:{Altimeter:30.167 SeaLevel:29.987 Station:25.108 Trend:Steady} Bat:{ConsoleVoltage:4.1484375 TransStatus:0} DewPoint:29 ET:{Today:0 LastMonth:0 LastYear:0} ExtraHumidity:[<nil> <nil> <nil> <nil> <nil> <nil> <nil>] ExtraTemp:[<nil> <nil> <nil> <nil> <nil> <nil> <nil>] Forecast:Increasing clouds with little temperature change. HeatIndex:56 Icons:[Cloud Partly Cloudy] InHumidity:44 InTemp:69.3 LeafTemp:[<nil> <nil> <nil> <nil>] LeafWetness:[<nil> <nil> <nil> <nil>] OutHumidity:31 OutTemp:60.1 Rain:{Accum:{Last15Min:0 LastHour:0 Last24Hours:0 Today:0 LastMonth:0.57 LastYear:1.54 Storm:0} Rate:0 StormStartDate:0001-01-01 00:00:00 +0000 UTC} SoilMoist:[<nil> <nil> <nil> <nil>] SoilTemp:[<nil> <nil> <nil> <nil>] SolarRad:32767 Sunrise:2017-09-16 06:37:00 -0700 PDT Sunset:2017-09-16 19:00:00 -0700 PDT THSWIndex:32767 UVIndex:25.5 Wind:{Avg:{Last2MinSpeed:5.4 Last10MinSpeed:4.1} Cur:{Dir:6 Speed:7} Gust:{Last10MinDir:360 Last10MinSpeed:0.8}} WindChill:60 nextArchRec:2072}
